### ISSUE TITLE
Custom protocol support

### ISSUE THREAD

**Issue by raman-kananovich** [open-rpc/schema-utils-js#587]
I want to use this library to work via a custom protocol that is based on a pub/sub mechanism.

It would be great to expose new versions of the `parseOpenRPCDocument` which accepts custom URI getters/resolvers. 

**Proposed functionality usage example**
`
    const parseOpenRPCDocument = makeCustomProtocolParseOpenRPCDocument(fetchCustomProtocol, resolveReferenceCustomProtocol);
`

Could you please provide your opinion regarding my proposal?

If it looks OK for you I can implement it and create a pull request.

**Comment by zcstarr** [comment]
@BelfordZ should weigh in here. It seems like you might want something like 
```
const parseOpenRpcDocument = makeBaseParseOpenRPCDocument(customProtcolHandler: (string)=>Promise<OpenRPC>)
parseOpenRpcDocument("custom://someotherprotocol, {dereference: mycustomRefHandler})
```
Then makeCustomParseOpenRPCDocument and the parseOpenRPCDocument share can share the same logic, where parseOpenRPCDocument looks like it does now essentially except instead  of returning the function it treturns a call to makeBaseParseOpenRPCDocument with the appropriate resolver. 

Then signature for makeParseOpenRPCDocument remains the same, but you have a way to access lower level functionality.

**Comment by raman-kananovich** [comment]
@zcstarr, thank you! This API covers my needs completely. 

How do you think if I can start its implementation?

**Comment by zcstarr** [comment]
@raman-kananovich you might actually do this as a stop gap , while we think over if the api change belongs inside schema-utils or not. You can start with the custom protocol and just deref the document then pass the dereffed document into to parseOpenRPCDocument. 

We think https://github.com/json-schema-tools/reference-resolver and 
https://github.com/json-schema-tools/referencer would be good places to start.

Inside the reference-resolver you'll need a PR here for your protocol would be immensely useful. Regardless about the api change, you'll need this logic in order to handle the custom protocol dereferencing. I'd start there.

**Comment by raman-kananovich** [comment]
@zcstarr, thank you! As you have proposed I am starting from reference-resolver.

**Comment by raman-kananovich** [comment]
Hello @zcstarr, could you please help me with the question regarding signing CLA? Can you provide a link to the instruction on how to do it. I have tried to google this topic, but the answers are different.

**Comment by zcstarr** [comment]
@raman-kananovich  don't worry about it, there is no CLA, that portion of the contributing.md is stale.

**Comment by raman-kananovich** [comment]
@zcstarr, thank you!

**Comment by raman-kananovich** [comment]
I have created a pull request to reference-reolver. I hope that I have done it in the right way.

@zcstarr, could you please take a look at my PR https://github.com/json-schema-tools/reference-resolver/pull/146 ?
